version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always    
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=fido.com,www.fido.com
